//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstForest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int num_track { get; set; }
        public int duration { get; set; }
        public System.DateTime DateReleased { get; set; }
        public double Price { get; set; }
        public string Genre { get; set; }
    }
}
